# Generated by Django 3.2 on 2021-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0002_search_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='id',
        ),
        migrations.AddField(
            model_name='search',
            name='uid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
