# Generated by Django 3.2 on 2021-04-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0004_alter_search_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
    ]
