# Generated by Django 3.2 on 2021-04-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0007_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
