# Generated by Django 3.2 on 2021-04-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrs', '0010_remove_searchmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to=settings.AUTH_USER_MODEL),
        ),
    ]
