# Generated by Django 3.2 on 2021-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0012_alter_searchmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='uid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
