# Generated by Django 3.2 on 2021-04-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0013_auto_20210414_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchModel',
        ),
    ]
