# Generated by Django 3.2 on 2021-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrs', '0014_delete_searchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(blank=True, max_length=100, null=True)),
                ('song_artist', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
