# Generated by Django 3.2 on 2021-04-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0016_searchmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='user',
        ),
    ]
