# Generated by Django 3.2 on 2021-04-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0020_feedbackmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
    ]
