# Generated by Django 3.2 on 2021-04-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0023_ratemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rateModel',
        ),
    ]
