# Generated by Django 3.2 on 2021-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0024_delete_ratemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
