# Generated by Django 3.2 on 2021-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0025_feedbackmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='rating',
            field=models.FloatField(),
        ),
    ]
